products = [
    {
        "id": 1,
        "class_id": 1,
        "name": "Heavy Duty Air Compressor 24L",
        "category": "Air Compressor",
        "price": 1250000,
        "old_price": 1450000,
        "stock": 8,
        "rating": 4.6,
        "sold": 124,
        "description": "Kompresor angin 24 liter dengan tenaga 1HP. Cocok untuk bengkel motor, bengkel las, atau kebutuhan pengecatan. Menghasilkan tekanan angin stabil dan cepat terisi.",
        "specs": ["Kapasitas: 24 Liter", "Power: 1 HP", "Tekanan: 8 Bar / 115 PSI", "Kecepatan: 2850 RPM"],
        "tags": ["kompresor", "angin", "bengkel", "cat"],
        "image_url": "/products/9.png"
    },
    {
        "id": 2,
        "class_id": 2,
        "name": "Professional Angle Grinder 4 inch",
        "category": "Angle Grinder",
        "price": 350000,
        "old_price": 450000,
        "stock": 25,
        "rating": 4.7,
        "sold": 450,
        "description": "Mesin gerinda tangan 4 inch (100mm) yang ringan namun bertenaga. Dilengkapi pelindung percikan dan handle tambahan untuk kontrol maksimal saat memotong besi atau keramik.",
        "specs": ["Daya: 540W", "Diameter pisau: 100mm", "Kecepatan tanpa beban: 12000 RPM", "Berat: 1.6 kg"],
        "tags": ["gerinda", "potong", "besi", "keramik"],
        "image_url": "/products/8.png"
    },
    {
        "id": 3,
        "class_id": 3,
        "name": "Camping Survival Axe",
        "category": "Axe",
        "price": 150000,
        "old_price": 180000,
        "stock": 30,
        "rating": 4.5,
        "sold": 89,
        "description": "Kapak outdoor dengan handle fiberglass anti-slip yang ergonomis. Mata kapak terbuat dari baja karbon berkualitas tinggi, tajam, dan tahan karat.",
        "specs": ["Bahan: High Carbon Steel", "Handle: Fiberglass rubber", "Panjang: 35 cm", "Berat: 600 gram"],
        "tags": ["kapak", "camping", "outdoor", "potong kayu"],
        "image_url": "/products/7.png"
    },
    {
        "id": 4,
        "class_id": 4,
        "name": "Steel Ball Bearing 6204",
        "category": "Ball Bearing",
        "price": 45000,
        "old_price": None,
        "stock": 150,
        "rating": 4.9,
        "sold": 890,
        "description": "Bantalan peluru (ball bearing) presisi tinggi untuk mengurangi gesekan pada mesin. Material baja krom tahan lama untuk berbagai keperluan industri dan otomotif.",
        "specs": ["Tipe: 6204", "Diameter dalam: 20 mm", "Diameter luar: 47 mm", "Tebal: 14 mm"],
        "tags": ["bearing", "laher", "mesin", "suku cadang"],
        "image_url": "/products/6.png"
    },
    {
        "id": 5,
        "class_id": 5,
        "name": "Cordless Drill 20V Lithium Ion",
        "category": "Cordless Drill",
        "price": 899000,
        "old_price": 1199000,
        "stock": 14,
        "rating": 4.8,
        "sold": 312,
        "description": "Bor cordless 20V untuk kebutuhan rumah, workshop, dan proyek ringan. Dilengkapi baterai lithium-ion yang tahan lama dan fast charging.",
        "specs": ["20V Lithium Ion", "2 speed mode", "LED light", "Ergonomic grip", "Torsi maksimal: 30 N.m"],
        "tags": ["bor", "cordless", "perkakas", "hardware"],
        "image_url": "https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=800&q=80"
    },
    {
        "id": 6,
        "class_id": 6,
        "name": "Steel Wrecking Crowbar 60cm",
        "category": "Crowbar",
        "price": 85000,
        "old_price": 110000,
        "stock": 42,
        "rating": 4.6,
        "sold": 156,
        "description": "Linggis besi solid dengan ujung pencabut paku. Sangat cocok untuk pekerjaan pembongkaran kayu, bangunan, dan paku ukuran besar.",
        "specs": ["Bahan: Solid Forged Steel", "Panjang: 60 cm", "Bentuk: Hexagonal", "Warna: Hitam anti karat"],
        "tags": ["linggis", "bongkar", "paku", "besi"],
        "image_url": "/products/crowbar.png"
    },
    {
        "id": 7,
        "class_id": 7,
        "name": "Dry Chemical Fire Extinguisher 3kg",
        "category": "Fire Extinguisher",
        "price": 275000,
        "old_price": 325000,
        "stock": 20,
        "rating": 4.9,
        "sold": 210,
        "description": "Alat Pemadam Api Ringan (APAR) serbuk kimia kering ukuran 3 kg. Ampuh memadamkan api kelas A, B, dan C. Sangat direkomendasikan untuk rumah, toko, dan gudang.",
        "specs": ["Kapasitas: 3 Kg", "Media: Dry Chemical Powder", "Kelas Api: A, B, C", "Tekanan: 14 Bar"],
        "tags": ["apar", "pemadam", "api", "safety"],
        "image_url": "/products/4.png"
    },
    {
        "id": 8,
        "class_id": 8,
        "name": "LED Tactical Flashlight 2000 Lumens",
        "category": "Flashlight",
        "price": 195000,
        "old_price": 250000,
        "stock": 55,
        "rating": 4.8,
        "sold": 640,
        "description": "Senter taktis LED super terang dengan output hingga 2000 lumens. Tahan air, dapat di-zoom, dan menggunakan baterai rechargeable 18650.",
        "specs": ["Brightness: 2000 Lumens", "Bahan: Aluminum Alloy", "Waterproof: IPX6", "Mode: High, Low, Strobe"],
        "tags": ["senter", "led", "tactical", "terang"],
        "image_url": "/products/3.png"
    },
    {
        "id": 9,
        "class_id": 9,
        "name": "Industrial Hot Glue Gun 100W",
        "category": "Hot Glue Gun",
        "price": 120000,
        "old_price": 150000,
        "stock": 38,
        "rating": 4.5,
        "sold": 280,
        "description": "Tembakan lem lilin panas daya 100W yang cepat melelehkan lem. Terdapat saklar on/off dan dudukan kawat agar aman saat diletakkan.",
        "specs": ["Daya: 100 Watt", "Tegangan: 110-240V", "Untuk lem stick besar (11mm)", "Lama pemanasan: 3-5 menit"],
        "tags": ["lem", "tembak", "glue gun", "kerajinan"],
        "image_url": "/products/2.png"
    },
    {
        "id": 10,
        "class_id": 10,
        "name": "Surge Protector Power Strip 5 Outlets",
        "category": "Power Strip",
        "price": 185000,
        "old_price": 210000,
        "stock": 65,
        "rating": 4.7,
        "sold": 520,
        "description": "Stop kontak cabang 5 dengan proteksi anti petir (surge protector). Aman digunakan untuk perangkat elektronik komputer, TV, maupun alat perkakas berdaya sedang.",
        "specs": ["Jumlah lubang: 5 Socket", "Kabel: 2 Meter", "Kapasitas maksimal: 2500W / 10A", "Surge Protection: Ya"],
        "tags": ["stop kontak", "colokan", "listrik", "kabel"],
        "image_url": "/products/1.png"
    }
]
